const papers = [
  {
    id: '1',
    title: 'Board Exam',
    description: 'ICSE Math 2024 board paper',
    chapters: ['All'],
    author: 'Steve',
    date: '5th August',
    views: 1000,
    rating: 4.5,
    thumbnailUrl: `https://picsum.photos/seed/${Math.random()}1/225/400`,
    board: 'ICSE',
    subject: 'Math',
    school: 'XYZ Public School',
  },
  {
    id: '2',
    title: 'Worksheet',
    description: 'Physics Worksheet 2023',
    chapters: ['Ch. 1', 'Ch. 2'],
    author: 'Alex',
    date: '12th July',
    views: 800,
    rating: 4.2,
    thumbnailUrl: `https://picsum.photos/seed/${Math.random()}2/225/400`,
    board: 'CBSE',
    subject: 'Physics',
    school: 'Delhi Public School',
  },
  {
    id: '3',
    title: 'Cheatsheet',
    description: 'Chemistry Quick Notes',
    chapters: ['Organic'],
    author: 'Sam',
    date: '20th June',
    views: 500,
    rating: 4.8,
    thumbnailUrl: `https://picsum.photos/seed/${Math.random()}3/225/400`,
    board: 'ICSE',
    subject: 'Chemistry',
    school: 'St. Xavier’s',
  },
  {
    id: '4',
    title: 'Sample Paper',
    description: 'Math Sample 2022',
    chapters: ['All'],
    author: 'Riya',
    date: '3rd May',
    views: 600,
    rating: 4.0,
    thumbnailUrl: `https://picsum.photos/seed/${Math.random()}4/225/400`,
    board: 'CBSE',
    subject: 'Math',
    school: 'Delhi Public School',
  },
  {
    id: '5',
    title: 'Revision Notes',
    description: 'Biology Revision Notes',
    chapters: ['Ch. 1', 'Ch. 3'],
    author: 'John',
    date: '15th April',
    views: 700,
    rating: 4.3,
    thumbnailUrl: `https://picsum.photos/seed/${Math.random()}5/225/400`,
    board: 'State',
    subject: 'Biology',
    school: 'XYZ Public School',
  },
  {
    id: '6',
    title: 'Past Paper',
    description: 'Physics Past Paper 2021',
    chapters: ['Ch. 1', 'Ch. 2', 'Ch. 3'],
    author: 'Emma',
    date: '10th March',
    views: 900,
    rating: 4.6,
    thumbnailUrl: `https://picsum.photos/seed/${Math.random()}6/225/400`,
    board: 'IGCSE',
    subject: 'Physics',
    school: 'St. Xavier\'s',
  },
  {
    id: '7',
    title: 'Mock Test',
    description: 'Chemistry Mock Test 2023',
    chapters: ['Organic', 'Inorganic'],
    author: 'Liam',
    date: '22nd February',
    views: 400,
    rating: 4.1,
    thumbnailUrl: `https://picsum.photos/seed/${Math.random()}7/225/400`,
    board: 'IB',
    subject: 'Chemistry',
    school: 'Oakridge International',
  },

];

export default papers;
export const boards = ['ICSE', 'CBSE', 'State', 'IGCSE', 'IB'];
export const subjects = ['Math', 'Physics', 'Chemistry', 'Biology'];
export const schools = ['XYZ Public School', 'Delhi Public School', 'St. Xavier’s'];